name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-clojars:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 2.9.1

      # - name: Generate pom.xml
      #   run: lein install

      # - uses: jlesquembre/clojars-publish-action@0.4
      #   env:
      #     USE_GIT_REF: false
      #     CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      #     CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
