name: Test

on:
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: "21.2.0"
          java: java11

      - name: Install bb
        run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          ./install --version 0.6.0 --static --dir /usr/local/bin

      - name: Run native tests
        run: bb native-image-test
